app_base_package=xxx.business
app_module_package=xxx.business.module

app_default_module=user

app_local_server_tag=
app_center_server_tag=center
app_center_server_url=

plugin_mvc=spring
plugin_transaction=spring
plugin_route=spring

param_loginid=loginId
param_companycode=companyCode
param_accesstoken=accessToken